name: Publish to Azure

# Run on call from other workflow
on:
  workflow_call:
    inputs:
      envName:
        description: "The environment to deploy to (Development or Production)"
        required: true
        default: Development
        type: environment
      envUrl:
        description: "The URL to deploy to"
        required: true
        default: "https://demo-actions-dev.azurewebsites.net/"
        type: string
      slotName:
        description: "The Azure Web App Slot to deploy the app to"
        required: true
        default: "dev"
        type: string
      artifactName:
        description: "The name of the artifact uploaded with actions/upload-artifact"
        required: true
        type: string
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true

jobs:
  deploy:
    
    name: Deploy to ${{ inputs.envName }}
    environment: 
      name: ${{ inputs.envName }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    runs-on: ubuntu-latest

    steps:

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifactName }}
        path: ./demoActions
        
    - name: 'Deploy to ${{ inputs.envName }} '
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'demo-actions(dev)'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./demoActions 
        slot-name: ${{ inputs.slotName }}
